FROM nvidia/cuda:12.6.2-cudnn-runtime-ubuntu22.04

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    git \
    wget \
    ffmpeg \
    libsndfile1-dev \
    python3 \
    python3-pip \
    && apt-get clean && pip3 install --upgrade pip

COPY Code/hifi-gan/ /workspace/hifi-gan/

WORKDIR /workspace/hifi-gan
RUN pip3 install -r requirements.txt

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

COPY DataSet/LJSpeech-1.1/wavs /workspace/hifi-gan/LJSpeech-1.1/wavs

EXPOSE 6006

# Define the command to run training
CMD ["python3", "train.py", "--config", "config_v1.json"]